name: Deploy

on:
  push:
    branches: [src]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          hugo-version: latest
          extended: true

      - name: Install Yarn dependencies
        uses: borales/actions-yarn@v2.3.0

      - name: Build site with Hugo
        run: hugo --minify --buildFuture

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
